# Generated by Django 4.1 on 2022-08-08 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_article_article_category_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
        migrations.DeleteModel(
            name='Article_Category',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='Article',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
