# Generated by Django 4.1 on 2022-08-08 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_article_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='Article',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
