# Generated by Django 4.1 on 2022-08-08 03:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_comment_article_delete_article_delete_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headlines', models.CharField(max_length=255)),
                ('body', models.TextField(max_length=255)),
                ('Article_pic', models.FileField(upload_to='Articles/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png'], message='Please Upload The Fellowing Image Format jpg ord png')], verbose_name='Article Pic')),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.article_category')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': ['pub_date', 'headlines'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(max_length=255)),
                ('comment_date', models.DateField(auto_now_add=True)),
                ('Article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article', to='blog.article')),
            ],
            options={
                'get_latest_by': ['comment_date'],
            },
        ),
    ]
