# Generated by Django 4.1 on 2022-08-10 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_publisher_remove_article_author_delete_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publisher',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_publisher', to='blog.publisher'),
        ),
    ]
