# Generated by Django 4.1 on 2022-08-10 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_remove_article_publisher_article_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comments',
            field=models.CharField(max_length=255),
        ),
    ]
