# Generated by Django 4.1 on 2022-08-12 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_alter_article_pub_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'get_latest_by': ['pub_date']},
        ),
    ]
