# Generated by Django 4.1 on 2022-08-12 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_alter_article_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['pub_date']},
        ),
    ]
